### ISSUE TITLE
I've subscribed to the mod but it's not in gmod anymore

### ISSUE THREAD

**Issue by MarshaMark** [TheOnly8Z/sbtm#5]
Can u please fix it because this has never happened to me on any other mod

**Comment by TheOnly8Z** [comment]
Likely either you are in singleplayer, or you have too many addons and reached the lua file limit. Try disabling all other addons first.

**Comment by MarshaMark** [comment]
Well actually my client was bugged for the session and got fixed after I
restarted my game.
